---
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: $DB_INSTANCE_ID 
spec:
  allocatedStorage: 5 
  autoMinorVersionUpgrade: false
  availabilityZone: eu-west-1a 
  backupRetentionPeriod: 14 
  copyTagsToSnapshot: false
  dbInstanceClass: db.t3.micro 
  dbInstanceIdentifier: $DB_INSTANCE_ID 
  dbName: $DB_NAME 
  dbSubnetGroupName: $DB_SUBNET_GROUP_NAME 
  engine: postgres 
  engineVersion: "14.1" 
  deletionProtection: true
  storageEncrypted: false
  masterUsername: root 
  masterUserPassword:
    namespace: $MASTER_USER_PASS_SECRET_NAMESPACE 
    name: $MASTER_USER_PASS_SECRET_NAME 
    key: $MASTER_USER_PASS_SECRET_KEY 
  multiAZ: False