---
apiVersion: kms.services.k8s.aws/v1alpha1
kind: Key
metadata:
  name: $KEY_NAME 
spec:
  bypassPolicyLockoutSafetyCheck: false
  description: "Key created by ACK tests"
  multiRegion: false 
  tags:
  - tagKey: $KMS_KEY_TAG_KEY 
    tagValue: $KMS_KEY_TAG_VALUE 
