---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Instance
metadata:
  name: $INSTANCE_NAME
spec:
  imageID: $INSTANCE_AMI_ID
  instanceType: $INSTANCE_TYPE
  subnetID: $INSTANCE_SUBNET_ID
  securityGroupIDs:
  - $SECURITY_GROUP_ID
  monitoring: 
    enabled: false
  blockDeviceMappings:
  - deviceName: $DEVICE_NAME
    ebs: 
      deleteOnTermination: true
      encrypted: false
      volumeSize: $VOLUME_SIZE
      volumeType: $VOLUME_TYPE