---
apiVersion: kms.services.k8s.aws/v1alpha1
kind: CustomKeyStore
metadata:
  name: $CUSTOM_KEY_STORE_NAME 
spec:
  cloudHsmClusterID: $CLOUD_HSM_CLUSTER_ID 
  keyStorePassword: $KEY_STORE_PASSWORD 
  name: $CUSTOM_KEY_STORE_NAME 
  trustAnchorCertificate: $TRUST_ANCHOR_CERTIFICATE 