apiVersion: eks.services.k8s.aws/v1alpha1
kind: Cluster
metadata:
  name: $CLUSTER_NAME #Change the Cluster Name
spec:
  name: $CLUSTER_NAME #Change the Cluster Name
  roleARN: $CLUSTER_ROLE #Change the Cluster Role
  resourcesVPCConfig:
    endpointPrivateAccess: true
    endpointPublicAccess: false
    subnetIDs:
      - "$PUBLIC_SUBNET_1" #Change the first Subnet ID
      - "$PUBLIC_SUBNET_2" #Change the second Subnet ID
  version: $KUBERNETES_VERSION #Change the Kubernetes Version
