---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  name: $POLICY_NAME
spec:
  name: $POLICY_NAME
  description: $POLICY_DESCRIPTION
  #This example Policy allows to list all S3 Buckets
  policyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"s3:ListAllMyBuckets","Resource":"arn:aws:s3:::*"},{"Effect":"Allow","Action":["s3:List*"],"Resource":["*"]}]}'
  tags:
    - key: $IAM_ROLE_TAG_KEY
      value: $IAM_ROLE_TAG_VALUE