#This Lifecycle Rule expires images older than 14 days
---
apiVersion: ecr.services.k8s.aws/v1alpha1
kind: Repository
metadata:
  name: $REPOSITORY_NAME
spec:
  name: $REPOSITORY_NAME
  lifecyclePolicy: '{"rules":[{"rulePriority":1,"description":"Expire images older than 14 days","selection":{"tagStatus":"untagged","countType":"sinceImagePushed","countUnit":"days","countNumber":14},"action":{"type":"expire"}}]}'
