apiVersion: ec2.services.k8s.aws/v1alpha1
kind: DHCPOptions
metadata:
  name: $DHCP_OPTIONS_NAME
spec:
  dhcpConfigurations:
    - key: $DHCP_KEY_1
      values:
        - $DHCP_VAL_1
  tagSpecifications:
  - resourceType: "dhcpoptions"
    tags:
    - key: $DHCP_TAG_KEY
      value: $DHCP_TAG_VALUE