apiVersion: ec2.services.k8s.aws/v1alpha1
kind: RouteTable
metadata:
  name: $ROUTE_TABLE_NAME
spec:
  routes:
    - destinationCIDRBlock: $DEST_CIDR_BLOCK
      gatewayID: $IGW_ID
    - destinationCIDRBlock: $DEST_CIDR_BLOCK
      natGatewayID: $NGW_ID
  vpcID: $VPC_ID
  tagSpecifications:
  - resourceType: "routetable"
    tags:
    - key: $ROUTE_TABLE_TAG_KEY
      value: $ROUTE_TABLE_TAG_VALUE